### ISSUE TITLE
Functionality of no datapoints on the chart

### ISSUE THREAD

**Issue by szymon5x** [ddamiankowalski/light-trading-chart#2]
I want to submit a feature request that would support chart without any data. 

The chart could have axes from -100% to 100%, the current value at 0 and the color gray. In this configuration, no dates should be displayed.

If this is a problem or you don't have time at the moment, I will be happy to implement this functionality and create a Pull Request.

**Comment by ddamiankowalski** [comment]
Absolutely! Thank you for your contribution to the project :) I'll try to implement this feature in the upcoming days

**Comment by ddamiankowalski** [comment]
@szymon5x please check out the latest changes in version 2.0.30 :)
